// Domain models for on-device AI insight reports.

/// A complete insight report generated from journal data.
class InsightReport {
  final DateTime generatedAt;
  final DateTime rangeStart;
  final DateTime rangeEnd;
  final int totalEntries;
  final int activeDays;
  final int totalTrackedMinutes;

  /// Time spent per activity tag (label → minutes).
  final Map<String, int> timeByActivity;

  /// Mood frequency across the range (label → count).
  final Map<String, int> moodFrequency;

  /// Mood trend: ordered list of (date, dominant mood) pairs.
  final List<MoodDayPoint> moodTimeline;

  /// Correlations between activities and moods.
  final List<MoodActivityCorrelation> correlations;

  /// Detected patterns in the data.
  final List<InsightPattern> patterns;

  /// Natural-language summary paragraphs (generated by LLM or template).
  final String narrative;

  /// Whether the narrative was generated by an on-device LLM (true)
  /// or by the template engine (false).
  final bool isLlmGenerated;

  const InsightReport({
    required this.generatedAt,
    required this.rangeStart,
    required this.rangeEnd,
    required this.totalEntries,
    required this.activeDays,
    required this.totalTrackedMinutes,
    required this.timeByActivity,
    required this.moodFrequency,
    required this.moodTimeline,
    required this.correlations,
    required this.patterns,
    required this.narrative,
    this.isLlmGenerated = false,
  });
}

/// A single day's dominant mood for timeline charting.
class MoodDayPoint {
  final DateTime date;
  final String dominantMood;
  final int entryCount;

  const MoodDayPoint({
    required this.date,
    required this.dominantMood,
    required this.entryCount,
  });
}

/// Correlation between an activity and the moods experienced during it.
class MoodActivityCorrelation {
  final String activity;
  final Map<String, int> moodDistribution; // mood label → count
  final String? dominantMood;
  final int totalMinutes;

  const MoodActivityCorrelation({
    required this.activity,
    required this.moodDistribution,
    this.dominantMood,
    required this.totalMinutes,
  });
}

/// A detected pattern or insight.
class InsightPattern {
  final PatternType type;
  final String title;
  final String description;
  final double? confidence; // 0.0–1.0

  const InsightPattern({
    required this.type,
    required this.title,
    required this.description,
    this.confidence,
  });
}

enum PatternType {
  timeWaste,
  moodTrend,
  activityMoodLink,
  consistency,
  peakProductivity,
  suggestion,
}
